[package]
name = "izquiratops-site"
version = "0.1.0"
edition = "2021"

[dependencies]
tera = "1"
actix-web = "4"
actix-web-lab = "0.19"
actix-files = "0.6.2"
ignore = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
markdown = "0.3.0"